language: python
python:
  - 2.6
  - 2.7
  - 3.4
env:
  - DJANGO=django==1.6.11
  - DJANGO=django==1.7.11
  - DJANGO=django==1.8.8
  - DJANGO=django==1.9.1
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=django==1.7.11
    - python: 2.6
      env: DJANGO=django==1.8.8
    - python: 2.6
      env: DJANGO=django==1.9.1
  fast_finish: true
install:
  - travis_retry pip install $DJANGO
  - pip install -e .
script: python runtests.py
notifications:
  email: false
